### ISSUE TITLE
Receive GPS from client and update the game state.

### ISSUE THREAD

**Issue by cennydavidsson** [ThePursuit/Server-Parse#1]
The server need to have a function that takes a players gps and id and updates the state of the game, alternative an player object. The function should also on success return the updated state to the client.

Use branch:  https://github.com/ThePursuit/Server-Parse/tree/feature/updateGame

**Comment by cbenett** [comment]
updateGame is done. Changed from our own class Coordinates to the Parse-builtin class GeoPoint.  Had some problems with saving the Game object synchronous. It should now work as intended.
