### ISSUE TITLE
Join a created game.

### ISSUE THREAD

**Issue by cennydavidsson** [ThePursuit/Server-Parse#5]
There should be a function that takes a game id and joins that player to the game. The function should If success return the game state and a player id. 

If the game is in play the player should be put in a lobby until the game is completed.

Use branch: https://github.com/ThePursuit/Server-Parse/tree/feature/joinGame

**Comment by cbenett** [comment]
joinGame is done. Had some initial problems with saving the relations aswell as saving the object synchronous
