### ISSUE TITLE
Catching the prey.

### ISSUE THREAD

**Issue by cennydavidsson** [ThePursuit/Server-Parse#6]
There should be a function that takes an player id and if that player is close enough to the prey then the prey is caught and the game is over, the state of the game should be updated. The function should return if the caught was successful and if not give the player a penalty.

Use branch: https://github.com/ThePursuit/Server-Parse/tree/feature/tryCatch

**Comment by cbenett** [comment]
Will start working on this function the afternoon of 17/3.
