### ISSUE TITLE
Add rules to a game.

### ISSUE THREAD

**Issue by cennydavidsson** [ThePursuit/Server-Parse#9]
After creating a game the rules should be applied. So there need to be a function to set the rules for the game and creates a rules object and adds it to the game object.

Use branch: https://github.com/ThePursuit/Server-Parse/tree/feature/setRules

**Comment by cennydavidsson** [comment]
This feature is done and needs testing.

**Comment by bzzandrea** [comment]
Looks like a good way to implement the functionality. Awaiting thorough testing.
There are some minor clean-up to be made, as for example the initial method and some minor spelling errors. I will correct this with commit.
